const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Behaviors.Timer,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.ObjectTypeName,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{map_selectors: 0},
	{Sprite: 0},
	{Texto: 0},
	{array_recipes: 0},
	{array_cauldron: 0},
	{Toque: 0},
	{AJAX: 0},
	{Teclado: 0},
	{cauldron: 0},
	{leaves_base: 0},
	{leaves: 0},
	{water_drop: 0},
	{fire_dust: 0},
	{fire_dust_base: 0},
	{water_drop_base: 0},
	{potions_bg: 0},
	{balloon: 0},
	{Cronômetro: 0},
	{player: 0},
	{recipe_scroll_icon: 0},
	{recipe_scroll: 0},
	{cooldown_day: 0},
	{cooldown_client: 0},
	{touch_dot: 0},
	{cauldron_ingredient: 0},
	{recipe_scroll_ingredients: 0},
	{scroll_close: 0},
	{potion_return: 0},
	{GAMEMASTER: 0},
	{button: 0},
	{ArrastarSoltar: 0},
	{family_ingredients: 0},
	{family_arrays: 0},
	{gold: 0},
	{day: 0},
	{value: 0},
	{array_name: 0},
	{player_mood: 0}
];

self.InstanceType = {
	map_selectors: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	array_recipes: class extends self.IArrayInstance {},
	array_cauldron: class extends self.IArrayInstance {},
	Toque: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	cauldron: class extends self.ISpriteInstance {},
	leaves_base: class extends self.ISpriteInstance {},
	leaves: class extends self.ISpriteInstance {},
	water_drop: class extends self.ISpriteInstance {},
	fire_dust: class extends self.ISpriteInstance {},
	fire_dust_base: class extends self.ISpriteInstance {},
	water_drop_base: class extends self.ISpriteInstance {},
	potions_bg: class extends self.ISpriteInstance {},
	balloon: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	recipe_scroll_icon: class extends self.ISpriteInstance {},
	recipe_scroll: class extends self.ISpriteInstance {},
	cooldown_day: class extends self.ISpriteInstance {},
	cooldown_client: class extends self.ISpriteInstance {},
	touch_dot: class extends self.ISpriteInstance {},
	cauldron_ingredient: class extends self.ISpriteInstance {},
	recipe_scroll_ingredients: class extends self.ISpriteInstance {},
	scroll_close: class extends self.ISpriteInstance {},
	potion_return: class extends self.ISpriteInstance {},
	GAMEMASTER: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	family_ingredients: class extends self.ISpriteInstance {},
	family_arrays: class extends self.IArrayInstance {}
}